version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
    volumes:
      - ./data:/var/lib/postgresql/data